org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512M
android.enableJetifier=true
android.useAndroidX=true
android.enableR8=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
