// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl4uzvsZ1m05Dw0U19vkcq6b1IqYHJOdA',
    appId: '1:176793005702:web:3be3d668ccca8df91eab07',
    messagingSenderId: '176793005702',
    projectId: 'the-postbox-game',
    authDomain: 'the-postbox-game.firebaseapp.com',
    databaseURL: 'https://the-postbox-game.firebaseio.com',
    storageBucket: 'the-postbox-game.firebasestorage.app',
      measurementId: 'G-JZ284NSHRQ'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUikjM8sLH4RqgRfKR7a7CWLVAYPhXSr8',
    appId: '1:176793005702:android:fbdc8d42630c3ffd',
    messagingSenderId: '176793005702',
    projectId: 'the-postbox-game',
    databaseURL: 'https://the-postbox-game.firebaseio.com',
    storageBucket: 'the-postbox-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH_6MxE42i6S62k_1jNczL9ckp40H_gFs',
    appId: '1:176793005702:ios:471dddd78becfe8c1eab07',
    messagingSenderId: '176793005702',
    projectId: 'the-postbox-game',
    databaseURL: 'https://the-postbox-game.firebaseio.com',
    storageBucket: 'the-postbox-game.firebasestorage.app',
    androidClientId: '176793005702-bm8k047sgolu4nt8iki6sj92sgm2971l.apps.googleusercontent.com',
    iosClientId: '176793005702-rmq2h89o58g1lbe6bnqtg9rnllu8gv80.apps.googleusercontent.com',
    iosBundleId: 'com.code418.postboxGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH_6MxE42i6S62k_1jNczL9ckp40H_gFs',
    appId: '1:176793005702:ios:471dddd78becfe8c1eab07',
    messagingSenderId: '176793005702',
    projectId: 'the-postbox-game',
    databaseURL: 'https://the-postbox-game.firebaseio.com',
    storageBucket: 'the-postbox-game.firebasestorage.app',
    androidClientId: '176793005702-bm8k047sgolu4nt8iki6sj92sgm2971l.apps.googleusercontent.com',
    iosClientId: '176793005702-rmq2h89o58g1lbe6bnqtg9rnllu8gv80.apps.googleusercontent.com',
    iosBundleId: 'com.code418.postboxGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeKYMv3YDu3MQNqbBsG3Z9-ITJSkd1BWM',
    appId: '1:176793005702:web:d5b26f69d318dc4b1eab07',
    messagingSenderId: '176793005702',
    projectId: 'the-postbox-game',
    authDomain: 'the-postbox-game.firebaseapp.com',
    databaseURL: 'https://the-postbox-game.firebaseio.com',
    storageBucket: 'the-postbox-game.firebasestorage.app',
  );
}
